event_login = 'event_login'
event_register = 'event_register'
event_popup_add_contact = 'event_popup_add_contact'
event_pressed_add_contact = 'event_pressed_add_contact'
event_send_message_client = 'event_send_message_client'
event_open_chat_window = 'event_open_chat_window'
event_closed_chat_window = 'event_closed_chat_window'